import { Order, MaterialItem, ContactInfo, PurchaseOrder } from '../types';
import { extractDataViaBackend } from './apiClient';

export class GeminiPDFExtractorService {
  private static instance: GeminiPDFExtractorService;
  private extractionInProgress: boolean = false;
  private lastProcessedFile: string | null = null;

  private constructor() {}

  public static getInstance(): GeminiPDFExtractorService {
    if (!GeminiPDFExtractorService.instance) {
      GeminiPDFExtractorService.instance = new GeminiPDFExtractorService();
    }
    return GeminiPDFExtractorService.instance;
  }

  /**
   * Extract data from PDF using HRV AI
   */
  public async extractFromPDF(pdfFile: File): Promise<PurchaseOrder> {
    // Prevent duplicate calls for the same file
    const fileIdentifier = `${pdfFile.name}-${pdfFile.size}-${pdfFile.lastModified}`;
    
    if (this.extractionInProgress) {
      throw new Error('An extraction is already in progress. Please wait for it to complete.');
    }
    
    if (this.lastProcessedFile === fileIdentifier) {
      console.log('⚠️  This file was already processed. Skipping duplicate extraction.');
      throw new Error('This file has already been processed.');
    }
    
    this.extractionInProgress = true;
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      
      reader.onload = async () => {
        try {
          const base64String = reader.result as string;
          console.log('PDF file converted to base64, calling HRV AI...');
          
          const extractedData = await extractDataViaBackend(base64String);
          console.log('HRV AI extraction successful:', extractedData);
          
          this.lastProcessedFile = fileIdentifier;
          this.extractionInProgress = false;
          resolve(extractedData);
        } catch (error) {
          console.error('HRV AI extraction error:', error);
          this.extractionInProgress = false;
          reject(error);
        }
      };

      reader.onerror = () => {
        this.extractionInProgress = false;
        reject(new Error('Failed to read PDF file'));
      };

      reader.readAsDataURL(pdfFile);
    });
  }

  /**
   * Convert HRV AI extracted data to Order object
   */
  public convertGeminiDataToOrder(
    groqData: PurchaseOrder,
    uploadedBy: string,
    selectedSupplier?: ContactInfo,
    pdfFileData?: string,
    entity?: 'HRV' | 'NHG',
    poNumber?: string
  ): Partial<Order> {
    // Extract currency from HRV AI data or default to USD
    const extractedCurrency = groqData.currency || 'USD';

    // Convert HRV AI items to MaterialItem array
    const materials: MaterialItem[] = groqData.items.map((item, index) => ({
      id: `material_${Date.now()}_${index}`,
      name: item.materialName,
      description: item.materialGrade || undefined,
      sku: '',
      hsn: '',
      quantity: {
        value: item.quantity,
        unit: 'Kg' // Default unit, could be extracted if available
      },
      unitPrice: {
        amount: item.unitPrice,
        currency: extractedCurrency
      },
      totalPrice: {
        amount: item.totalPrice,
        currency: extractedCurrency
      },
      supplierUnitPrice: {
        amount: 0,
        currency: extractedCurrency
      },
      supplierTotalPrice: {
        amount: 0,
        currency: extractedCurrency
      },
      account: '',
      taxRate: 18, // Default tax rate
      taxAmount: (item.totalPrice * 0.18) // Calculate 18% tax by default
    }));

    // Calculate total quantity and amount
    const totalQuantity = materials.reduce((sum, item) => sum + item.quantity.value, 0);
    const totalAmount = groqData.totalAmount || materials.reduce((sum, item) => sum + item.totalPrice.amount, 0);

    // Note: Order ID will be generated by OrderContext in format YYYY-X
    // We don't set it here, let the context generate it sequentially

    // Create order object
    const order: Partial<Order> = {
      // orderId will be auto-generated by createOrder function
      createdAt: new Date().toISOString(),
      createdBy: {
        userId: uploadedBy,
        name: 'System User',
        role: 'Employee'
      },
      status: 'PO_Received_from_Client',
      
      // Customer information from HRV AI extraction
      customer: {
        name: groqData.customerName || 'Unknown Customer',
        address: groqData.customerAddress || 'Address not provided',
        country: 'India', // Default
        email: groqData.customerEmail || 'customer@example.com',
        phone: groqData.customerContact || 'N/A',
        gstin: groqData.customerGstin || undefined
      },
      
      // Supplier information - only set if user manually selects one
      supplier: selectedSupplier || null,
      
      // Material information
      materialName: materials[0]?.name || 'Unknown Material',
      materials: materials,
      
      // Pricing information
      priceToCustomer: {
        amount: totalAmount,
        currency: extractedCurrency
      },
      priceFromSupplier: {
        amount: 0, // To be filled by user
        currency: extractedCurrency
      },
      
      // Quantity information
      quantity: {
        value: totalQuantity,
        unit: 'Kg'
      },
      
      // Additional information
      poNumber: poNumber || groqData.poNumber || `PO-${Date.now()}`,
      deliveryTerms: groqData.shipmentDetails || 'FOB',
      notes: `Order created via HRV AI extraction on ${new Date().toLocaleDateString()}`,
      entity: entity || 'HRV',
      
      // Documents
      documents: pdfFileData ? {
        customerPO: {
          id: `doc_${Date.now()}`,
          filename: 'uploaded_po.pdf',
          uploadedAt: new Date().toISOString(),
          uploadedBy: {
            userId: uploadedBy,
            name: 'System User'
          },
          fileSize: pdfFileData.length,
          mimeType: 'application/pdf',
          data: pdfFileData
        }
      } : {},
      
      // Comments and logs
      comments: [],
      auditLogs: [],
      timeline: [
        {
          id: `timeline_${Date.now()}`,
          timestamp: new Date().toISOString(),
          event: 'Order Created',
          details: 'Order created from PDF upload using HRV AI extraction',
          actor: {
            userId: uploadedBy,
            name: 'System User',
            role: 'Employee'
          },
          status: 'PO_Received_from_Client'
        }
      ],
      
      // Approval information
      approvalRequests: [],
      
      // Assigned to
      assignedTo: {
        userId: uploadedBy,
        name: 'System User',
        role: 'Employee'
      },
    };

    return order;
  }
}

