import { Order, MaterialItem, ContactInfo, PurchaseOrder } from '../types';
import { extractDataViaBackend } from './apiClient';

export class GeminiPDFExtractorService {
  private static instance: GeminiPDFExtractorService;

  private constructor() {}

  public static getInstance(): GeminiPDFExtractorService {
    if (!GeminiPDFExtractorService.instance) {
      GeminiPDFExtractorService.instance = new GeminiPDFExtractorService();
    }
    return GeminiPDFExtractorService.instance;
  }

  /**
   * Extract data from PDF using Gemini AI
   */
  public async extractFromPDF(pdfFile: File): Promise<PurchaseOrder> {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      
      reader.onload = async () => {
        try {
          const base64String = reader.result as string;
          console.log('PDF file converted to base64, calling Gemini AI...');
          
          const extractedData = await extractDataViaBackend(base64String);
          console.log('Gemini AI extraction successful:', extractedData);
          
          resolve(extractedData);
        } catch (error) {
          console.error('Gemini extraction error:', error);
          reject(error);
        }
      };

      reader.onerror = () => {
        reject(new Error('Failed to read PDF file'));
      };

      reader.readAsDataURL(pdfFile);
    });
  }

  /**
   * Convert Gemini extracted data to Order object
   */
  public convertGeminiDataToOrder(
    geminiData: PurchaseOrder,
    uploadedBy: string,
    selectedSupplier?: ContactInfo,
    pdfFileData?: string
  ): Partial<Order> {
    // Extract currency from Gemini data or default to USD
    const extractedCurrency = geminiData.currency || 'USD';

    // Convert Gemini items to MaterialItem array
    const materials: MaterialItem[] = geminiData.items.map((item, index) => ({
      id: `material_${Date.now()}_${index}`,
      name: item.materialName,
      description: item.materialGrade || undefined,
      sku: '',
      hsn: '',
      quantity: {
        value: item.quantity,
        unit: 'Kg' // Default unit, could be extracted if available
      },
      unitPrice: {
        amount: item.unitPrice,
        currency: extractedCurrency
      },
      totalPrice: {
        amount: item.totalPrice,
        currency: extractedCurrency
      }
    }));

    // Calculate total quantity and amount
    const totalQuantity = materials.reduce((sum, item) => sum + item.quantity.value, 0);
    const totalAmount = geminiData.totalAmount || materials.reduce((sum, item) => sum + item.totalPrice.amount, 0);

    // Note: Order ID will be generated by OrderContext in format YYYY-X
    // We don't set it here, let the context generate it sequentially

    // Create order object
    const order: Partial<Order> = {
      // orderId will be auto-generated by createOrder function
      createdAt: new Date().toISOString(),
      createdBy: {
        userId: uploadedBy,
        name: 'System User',
        role: 'Employee'
      },
      status: 'PO_Received_from_Client',
      
      // Customer information from Gemini extraction
      customer: {
        name: geminiData.customerName || 'Unknown Customer',
        address: geminiData.customerAddress || 'Address not provided',
        country: 'India', // Default
        email: geminiData.customerEmail || 'customer@example.com',
        phone: geminiData.customerContact || 'N/A',
        gstin: geminiData.customerGstin || undefined
      },
      
      // Supplier information (from user selection or default)
      supplier: selectedSupplier || {
        name: 'Unknown Supplier',
        address: 'Address not provided',
        country: 'India',
        email: 'supplier@example.com',
        phone: 'N/A',
        gstin: undefined
      },
      
      // Material information
      materialName: materials[0]?.name || 'Unknown Material',
      materials: materials,
      
      // Pricing information
      priceToCustomer: {
        amount: totalAmount,
        currency: extractedCurrency
      },
      priceFromSupplier: {
        amount: 0, // To be filled by user
        currency: extractedCurrency
      },
      
      // Quantity information
      quantity: {
        value: totalQuantity,
        unit: 'Kg'
      },
      
      // Additional information
      poNumber: geminiData.poNumber || `PO-${Date.now()}`,
      deliveryTerms: geminiData.shipmentDetails || 'FOB',
      notes: `Order created via Gemini AI extraction on ${new Date().toLocaleDateString()}`,
      entity: 'HRV',
      
      // Documents
      documents: pdfFileData ? {
        customerPO: {
          id: `doc_${Date.now()}`,
          filename: 'uploaded_po.pdf',
          uploadedAt: new Date().toISOString(),
          uploadedBy: {
            userId: uploadedBy,
            name: 'System User'
          },
          fileSize: pdfFileData.length,
          mimeType: 'application/pdf',
          data: pdfFileData
        }
      } : {},
      
      // Comments and logs
      comments: [],
      auditLogs: [],
      timeline: [
        {
          id: `timeline_${Date.now()}`,
          timestamp: new Date().toISOString(),
          event: 'Order Created',
          details: 'Order created from PDF upload using Gemini AI extraction',
          actor: {
            userId: uploadedBy,
            name: 'System User',
            role: 'Employee'
          },
          status: 'PO_Received_from_Client'
        }
      ],
      
      // Approval information
      approvalRequests: [],
      
      // Assigned to
      assignedTo: {
        userId: uploadedBy,
        name: 'System User',
        role: 'Employee'
      },
    };

    return order;
  }
}

